hw03: mohammad_ashraf_yawar_161044123.o functions.o
	g++ mohammad_ashraf_yawar_161044123.o functions.o -o hw03
mohammad_ashraf_yawar_161044123.o: mohammad_ashraf_yawar_161044123.cpp structs_classes.h
	g++ -c mohammad_ashraf_yawar_161044123.cpp
functions.o: functions.cpp  structs_classes.h
	g++ -c functions.cpp
clean:
	rm *.o hw03